export type Lang = "en" | "ur";

const STRINGS = {
  en: {
    nav_about: "About",
    nav_services: "Services",
    nav_locations: "Locations",
    nav_faq: "FAQs",
    nav_book: "Book appointment",

    hero_eyebrow: "Consultant Nephrologist · Lahore",
    hero_name: "Dr. Irfan Ahmad",
    hero_creds: "M.B.B.S · MRCP · FRCP (Ireland)",
    hero_role: "Consultant Physician, Nephrologist & Transplant Specialist",
    hero_subtitle: "Specialist in Diabetes, Hypertension, Kidney Disease and Transplantation. Trained in Ireland and Liverpool, practising at Lahore Doctors Hospital and Farooq Hospital.",
    hero_cta_book: "Book an appointment",
    hero_cta_call: "Call clinic",
    hero_credential_title: "Internationally trained",
    hero_credential_sub: "Ireland · Liverpool · UK",

    stat_years: "Years of practice",
    stat_patients: "Patients treated",
    stat_transplants: "Transplants performed",
    stat_rating: "Patient rating",

    about_eyebrow: "About",
    about_title: "Two decades caring for the kidneys of Lahore.",
    about_body_1: "Dr. Irfan Ahmad is an Associate Professor of Nephrology at Akhtar Saeed Medical and Dental College, and a consultant at Lahore Doctors Hospital and Farooq Hospital. His work centres on advanced kidney care — chronic kidney disease, dialysis, and renal transplantation — alongside long-term management of diabetes and hypertension.",
    about_body_2: "He completed Higher Specialist Training in Nephrology in Ireland, holds a Diploma in Diabetes (UK) and is certified in Organ Transplantation from Liverpool. He is a Fellow of the Royal College of Physicians of Ireland.",

    spec_eyebrow: "Specializations",
    spec_title: "Areas of focus",
    spec_kidney: "Kidney Disease",
    spec_kidney_desc: "Chronic kidney disease, glomerular disorders, and dialysis access planning.",
    spec_transplant: "Transplant Care",
    spec_transplant_desc: "Pre- and post-transplant evaluation, immunosuppression, and long-term follow-up.",
    spec_diabetes: "Diabetes",
    spec_diabetes_desc: "Comprehensive diabetes management with focus on kidney protection.",
    spec_hyper: "Hypertension",
    spec_hyper_desc: "Resistant and secondary hypertension, including renovascular causes.",

    qual_eyebrow: "Training & Credentials",
    qual_title: "Qualifications",
    qual_mbbs: "M.B.B.S",
    qual_mbbs_inst: "King Edward Medical University, Lahore",
    qual_mrcp: "MRCP — Member, Royal College of Physicians",
    qual_mrcp_inst: "United Kingdom",
    qual_frcp: "FRCP — Fellow, Royal College of Physicians",
    qual_frcp_inst: "Ireland",
    qual_hst: "Higher Specialist Training in Nephrology",
    qual_hst_inst: "Republic of Ireland",
    qual_diab: "Diploma in Diabetes",
    qual_diab_inst: "United Kingdom",
    qual_tx: "Certified in Organ Transplantation",
    qual_tx_inst: "University of Liverpool",
    qual_assoc: "Associate Professor of Nephrology",
    qual_assoc_inst: "Akhtar Saeed Medical and Dental College",

    loc_eyebrow: "Where to find Dr. Ahmad",
    loc_title: "Hospital locations",
    loc_ldh: "Lahore Doctors Hospital",
    loc_ldh_addr: "152-A, Block G-1, Johar Town, Lahore",
    loc_ldh_hours: "Mon–Sat · 5:00 PM – 8:00 PM",
    loc_fh: "Farooq Hospital",
    loc_fh_addr: "Westwood Branch, Raiwind Road, Lahore",
    loc_fh_hours: "Mon, Wed, Fri · 11:00 AM – 2:00 PM",
    loc_directions: "Get directions",
    loc_call_reception: "Call reception",

    test_eyebrow: "Patient stories",
    test_title: "What patients say",
    test_1: "Dr. Ahmad explained my mother's dialysis options without rushing. We came in scared and left with a plan we understood.",
    test_1_name: "Ayesha K.",
    test_1_meta: "Daughter of patient",
    test_2: "Six years post-transplant and still thriving thanks to his follow-up. He never misses a detail.",
    test_2_name: "Tariq M.",
    test_2_meta: "Transplant recipient",
    test_3: "Finally got my blood pressure under control after years of trying. Calm, methodical, kind.",
    test_3_name: "Saima R.",
    test_3_meta: "Hypertension patient",

    faq_eyebrow: "Common questions",
    faq_title: "When should you see a nephrologist?",
    faq_1_q: "What does a nephrologist treat?",
    faq_1_a: "Nephrologists specialise in kidney health — including chronic kidney disease, kidney stones, dialysis, transplants, and the management of high blood pressure when it relates to kidney function.",
    faq_2_q: "When should I book a consultation?",
    faq_2_a: "If you have diabetes, persistent high blood pressure, swelling in the legs, foamy urine, family history of kidney disease, or have been told your creatinine is high — these are good reasons to come in.",
    faq_3_q: "Do I need a referral?",
    faq_3_a: "No referral is required. You can book directly. Bring any recent lab reports, imaging, and a list of medications.",
    faq_4_q: "What happens at the first visit?",
    faq_4_a: "A 30–45 minute consultation: review of history and reports, examination, and a discussion of next steps. Tests may be ordered if needed.",
    faq_5_q: "Is online consultation available?",
    faq_5_a: "Follow-up patients can request a phone consultation. First-time patients are seen in person to allow for proper examination.",

    book_step_hospital: "Hospital",
    book_step_time: "Date & time",
    book_step_details: "Your details",
    book_step_confirm: "Confirm",
    book_title: "Book an appointment",
    book_subtitle: "Most patients are seen within 3 working days.",
    book_choose_hospital: "Where would you like to be seen?",
    book_first_visit: "Is this a first visit or follow-up?",
    book_first: "First visit",
    book_followup: "Follow-up",
    book_choose_date: "Choose a date",
    book_choose_time: "Available time slots",
    book_morning: "Morning",
    book_afternoon: "Afternoon",
    book_evening: "Evening",
    book_no_slots: "No slots available",
    book_full_name: "Full name",
    book_phone: "Mobile number",
    book_cnic: "CNIC (optional)",
    book_age: "Age",
    book_gender: "Gender",
    book_male: "Male",
    book_female: "Female",
    book_other: "Other",
    book_reason: "Reason for visit",
    book_reason_ph: "Briefly describe your symptoms or concern…",
    book_continue: "Continue",
    book_back: "Back",
    book_confirm_btn: "Confirm appointment",
    book_summary: "Appointment summary",
    book_confirmed: "Appointment confirmed",
    book_confirmed_sub: "We've sent details to your phone. Please arrive 15 minutes early with your previous reports and a list of current medications.",
    book_booking_id: "Booking ID",
    book_add_calendar: "Add to calendar",
    book_done: "Done",

    foot_tag: "Care, continuity, kidney health.",
    foot_links: "Links",
    foot_contact: "Contact",
    foot_hours: "Clinic hours",
    foot_emergency: "For emergencies, please go to the nearest hospital A&E.",
    foot_copy: "© 2026 Dr. Irfan Ahmad. All rights reserved.",
  },
  ur: {
    nav_about: "تعارف",
    nav_services: "خدمات",
    nav_locations: "مقامات",
    nav_faq: "سوالات",
    nav_book: "اپائنٹمنٹ",

    hero_eyebrow: "ماہر امراضِ گردہ · لاہور",
    hero_name: "ڈاکٹر عرفان احمد",
    hero_creds: "M.B.B.S · MRCP · FRCP (Ireland)",
    hero_role: "کنسلٹنٹ فزیشن، نیفرولوجسٹ اور ٹرانسپلانٹ اسپیشلسٹ",
    hero_subtitle: "ذیابیطس، بلڈ پریشر، گردوں کے امراض اور ٹرانسپلانٹ کے ماہر۔ آئرلینڈ اور لیورپول سے تربیت یافتہ، لاہور ڈاکٹرز ہسپتال اور فاروق ہسپتال میں خدمات۔",
    hero_cta_book: "اپائنٹمنٹ بک کریں",
    hero_cta_call: "کلینک کال کریں",
    hero_credential_title: "بین الاقوامی تربیت یافتہ",
    hero_credential_sub: "آئرلینڈ · لیورپول",

    stat_years: "سالہ تجربہ",
    stat_patients: "مریضوں کا علاج",
    stat_transplants: "ٹرانسپلانٹس",
    stat_rating: "مریضوں کی رائے",

    about_eyebrow: "تعارف",
    about_title: "لاہور کے گردوں کی دو دہائیوں کی دیکھ بھال۔",
    about_body_1: "ڈاکٹر عرفان احمد اختر سعید میڈیکل اینڈ ڈینٹل کالج میں نیفرولوجی کے ایسوسی ایٹ پروفیسر ہیں، اور لاہور ڈاکٹرز ہسپتال اور فاروق ہسپتال میں کنسلٹنٹ ہیں۔",
    about_body_2: "انہوں نے آئرلینڈ سے نیفرولوجی میں ہائر اسپیشلسٹ ٹریننگ مکمل کی، یوکے سے ذیابیطس میں ڈپلومہ حاصل کیا، اور لیورپول سے آرگن ٹرانسپلانٹیشن میں سرٹیفیکیشن لی۔",

    spec_eyebrow: "خصوصی شعبے",
    spec_title: "مہارت کے شعبے",
    spec_kidney: "گردوں کے امراض",
    spec_kidney_desc: "دائمی گردہ کی بیماری، ڈائلیسس اور متعلقہ علاج۔",
    spec_transplant: "ٹرانسپلانٹ",
    spec_transplant_desc: "ٹرانسپلانٹ سے قبل و بعد کی دیکھ بھال اور فالو اپ۔",
    spec_diabetes: "ذیابیطس",
    spec_diabetes_desc: "ذیابیطس کا جامع علاج، گردوں کی حفاظت پر توجہ۔",
    spec_hyper: "بلڈ پریشر",
    spec_hyper_desc: "مزاحم اور ثانوی بلڈ پریشر کا علاج۔",

    qual_eyebrow: "تربیت و اسناد",
    qual_title: "اسناد",
    qual_mbbs: "M.B.B.S",
    qual_mbbs_inst: "کنگ ایڈورڈ میڈیکل یونیورسٹی، لاہور",
    qual_mrcp: "MRCP — رکن، رائل کالج آف فزیشنز",
    qual_mrcp_inst: "برطانیہ",
    qual_frcp: "FRCP — فیلو، رائل کالج آف فزیشنز",
    qual_frcp_inst: "آئرلینڈ",
    qual_hst: "نیفرولوجی میں ہائر اسپیشلسٹ ٹریننگ",
    qual_hst_inst: "آئرلینڈ",
    qual_diab: "ڈپلومہ ان ذیابیطس",
    qual_diab_inst: "برطانیہ",
    qual_tx: "آرگن ٹرانسپلانٹیشن سرٹیفکیٹ",
    qual_tx_inst: "یونیورسٹی آف لیورپول",
    qual_assoc: "ایسوسی ایٹ پروفیسر، نیفرولوجی",
    qual_assoc_inst: "اختر سعید میڈیکل اینڈ ڈینٹل کالج",

    loc_eyebrow: "ہم کہاں ملتے ہیں",
    loc_title: "ہسپتال کے مقامات",
    loc_ldh: "لاہور ڈاکٹرز ہسپتال",
    loc_ldh_addr: "152-A، بلاک G-1، جوہر ٹاؤن، لاہور",
    loc_ldh_hours: "پیر تا ہفتہ · شام 5 تا 8",
    loc_fh: "فاروق ہسپتال",
    loc_fh_addr: "ویسٹ ووڈ برانچ، رائے ونڈ روڈ، لاہور",
    loc_fh_hours: "پیر، بدھ، جمعہ · صبح 11 تا 2",
    loc_directions: "راستہ دیکھیں",
    loc_call_reception: "ریسپشن کال کریں",

    test_eyebrow: "مریضوں کی آراء",
    test_title: "مریض کیا کہتے ہیں",
    test_1: "ڈاکٹر صاحب نے میری والدہ کے ڈائلیسس کے سب آپشن تفصیل سے سمجھائے۔ ہم پریشان آئے، اطمینان سے گئے۔",
    test_1_name: "عائشہ ک.",
    test_1_meta: "مریضہ کی بیٹی",
    test_2: "ٹرانسپلانٹ کے چھ سال بعد بھی ٹھیک ہوں، ان کی فالو اپ کی بدولت۔",
    test_2_name: "طارق م.",
    test_2_meta: "ٹرانسپلانٹ ریسپینٹ",
    test_3: "آخرکار میرا بلڈ پریشر کنٹرول میں آیا۔ مہربان، تجربہ کار اور پرسکون۔",
    test_3_name: "صائمہ ر.",
    test_3_meta: "ہائپرٹینشن مریضہ",

    faq_eyebrow: "اکثر پوچھے گئے سوالات",
    faq_title: "نیفرولوجسٹ سے کب رجوع کریں؟",
    faq_1_q: "نیفرولوجسٹ کن امراض کا علاج کرتے ہیں؟",
    faq_1_a: "نیفرولوجسٹ گردوں کی صحت، ڈائلیسس، ٹرانسپلانٹ اور بلڈ پریشر کے ماہر ہوتے ہیں۔",
    faq_2_q: "کب اپائنٹمنٹ لینی چاہیے؟",
    faq_2_a: "ذیابیطس، بلڈ پریشر، ٹانگوں میں سوجن، یا کریٹینین زیادہ ہونے کی صورت میں رجوع کریں۔",
    faq_3_q: "کیا ریفرل ضروری ہے؟",
    faq_3_a: "نہیں، براہ راست بک کر سکتے ہیں۔ پرانی رپورٹیں اور دواؤں کی فہرست ساتھ لائیں۔",
    faq_4_q: "پہلی ملاقات میں کیا ہوگا؟",
    faq_4_a: "30–45 منٹ کی ملاقات: تاریخ، رپورٹس کا جائزہ، معائنہ اور آئندہ کے اقدامات۔",
    faq_5_q: "کیا آن لائن مشاورت دستیاب ہے؟",
    faq_5_a: "فالو اپ مریض فون پر مشاورت لے سکتے ہیں۔ پہلی ملاقات بالمشافہ ہوتی ہے۔",

    book_step_hospital: "ہسپتال",
    book_step_time: "تاریخ و وقت",
    book_step_details: "تفصیلات",
    book_step_confirm: "تصدیق",
    book_title: "اپائنٹمنٹ بک کریں",
    book_subtitle: "زیادہ تر مریضوں کو 3 دن میں دیکھا جاتا ہے۔",
    book_choose_hospital: "کہاں ملاقات کرنا چاہیں گے؟",
    book_first_visit: "پہلی ملاقات یا فالو اپ؟",
    book_first: "پہلی ملاقات",
    book_followup: "فالو اپ",
    book_choose_date: "تاریخ منتخب کریں",
    book_choose_time: "دستیاب اوقات",
    book_morning: "صبح",
    book_afternoon: "دوپہر",
    book_evening: "شام",
    book_no_slots: "کوئی وقت دستیاب نہیں",
    book_full_name: "پورا نام",
    book_phone: "موبائل نمبر",
    book_cnic: "شناختی کارڈ (اختیاری)",
    book_age: "عمر",
    book_gender: "جنس",
    book_male: "مرد",
    book_female: "خاتون",
    book_other: "دیگر",
    book_reason: "ملاقات کی وجہ",
    book_reason_ph: "علامات یا تشویش مختصراً لکھیں…",
    book_continue: "آگے",
    book_back: "واپس",
    book_confirm_btn: "اپائنٹمنٹ کنفرم کریں",
    book_summary: "اپائنٹمنٹ کا خلاصہ",
    book_confirmed: "اپائنٹمنٹ تصدیق شدہ",
    book_confirmed_sub: "تفصیلات آپ کے فون پر بھیج دی گئی ہیں۔ مہربانی فرما کر 15 منٹ پہلے پہنچیں۔",
    book_booking_id: "بکنگ آئی ڈی",
    book_add_calendar: "کیلنڈر میں شامل کریں",
    book_done: "ختم",

    foot_tag: "گردوں کی صحت — خیال، تسلسل، اعتبار۔",
    foot_links: "روابط",
    foot_contact: "رابطہ",
    foot_hours: "اوقاتِ کلینک",
    foot_emergency: "ایمرجنسی کی صورت میں قریبی ہسپتال کے ایمرجنسی ڈیپارٹمنٹ سے رجوع کریں۔",
    foot_copy: "© 2026 ڈاکٹر عرفان احمد۔ جملہ حقوق محفوظ ہیں۔",
  },
} as const;

export type StringKey = keyof typeof STRINGS.en;

export function useT(lang: Lang) {
  return (key: StringKey): string =>
    (STRINGS[lang] as Record<string, string>)[key] ?? STRINGS.en[key] ?? key;
}

export function formatDate(d: Date, lang: Lang): string {
  const months =
    lang === "ur"
      ? ["جنوری","فروری","مارچ","اپریل","مئی","جون","جولائی","اگست","ستمبر","اکتوبر","نومبر","دسمبر"]
      : ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return `${d.getDate()} ${months[d.getMonth()]} ${d.getFullYear()}`;
}
