export type Lang = "en" | "ur";

const STRINGS = {
  en: {
    nav_about: "About",
    nav_services: "Services",
    nav_locations: "Locations",
    nav_faq: "FAQs",
    nav_book: "Book appointment",

    hero_eyebrow: "Consultant Nephrologist · Lahore",
    hero_name: "Dr. Irfan Ahmad",
    hero_creds: "M.B.B.S · MRCPI · FRCPI · Specialist Training in Nephrology · Diploma in Diabetes UK",
    hero_role: "Consultant Physician, Nephrologist & Transplant Specialist",
    hero_subtitle: "Specialist in Diabetes, Hypertension, Kidney Disease and Transplantation. He has worked as a nephrologist at affiliated hospitals of the University of Queensland, Australia and in Brunei Darussalam. Now practising at Doctors Hospital and Medical Center Lahore and Farooq Hospital DHA Lahore.",
    hero_cta_book: "Book an appointment",
    hero_cta_call: "Call clinic",
    hero_credential_title: "Internationally trained",
    hero_credential_sub: "UK · Australia · Brunei",

    stat_years: "Years of practice",
    stat_patients: "Patients treated",
    stat_transplants: "Transplants performed",
    stat_rating: "Patient rating",

    about_eyebrow: "About",
    about_title: "More than a decade caring for kidney and diabetes patients.",
    about_body_1: "Dr. Irfan Ahmad is an Associate Professor of Nephrology at Akhtar Saeed Medical and Dental College Lahore. He works as a consultant physician and nephrologist at Doctors Hospital and Medical Center Lahore and Farooq Hospital DHA Lahore. His work centres on advanced kidney care — chronic kidney disease, dialysis, and renal transplantation — alongside long-term management of diabetes and hypertension.",
    about_body_2: "He completed his MRCPI and FRCPI from the Royal College of Physicians of Ireland and is certified in organ transplantation from the University of Liverpool, UK. He also holds a Diploma in Diabetes (UK).",

    spec_eyebrow: "Specializations",
    spec_title: "Areas of focus",
    spec_kidney: "Kidney Disease",
    spec_kidney_desc: "Acute and chronic kidney disease, glomerular disorders, haemodialysis, peritoneal dialysis, and kidney stones.",
    spec_transplant: "Transplant Care",
    spec_transplant_desc: "Evaluation and preparation for kidney transplant, post-transplant care, immunosuppression, and long-term follow-up.",
    spec_diabetes: "Diabetes",
    spec_diabetes_desc: "Comprehensive diabetes management with focus on kidney protection.",
    spec_hyper: "Hypertension",
    spec_hyper_desc: "Essential, secondary and resistant hypertension, including renovascular causes.",
    spec_intervention: "Intervention",
    spec_intervention_desc: "Temporary and permanent dialysis catheter insertion and renal biopsy.",

    qual_eyebrow: "Training & Credentials",
    qual_title: "Qualifications",
    qual_mbbs: "M.B.B.S",
    qual_mbbs_inst: "Hamdard University, Karachi",
    qual_mrcp: "MRCPI — Member, Royal College of Physicians of Ireland",
    qual_mrcp_inst: "Royal College of Physicians of Ireland",
    qual_frcp: "FRCPI — Fellow, Royal College of Physicians of Ireland",
    qual_frcp_inst: "Royal College of Physicians of Ireland",
    qual_hst: "Higher Specialist Training in Nephrology",
    qual_hst_inst: "International specialist training",
    qual_diab: "Diploma in Diabetes",
    qual_diab_inst: "United Kingdom",
    qual_tx: "Certified in Organ Transplantation",
    qual_tx_inst: "University of Liverpool",
    qual_assoc: "Associate Professor of Nephrology",
    qual_assoc_inst: "Akhtar Saeed Medical and Dental College",

    loc_eyebrow: "Where to find Dr. Ahmad",
    loc_title: "Hospital locations",
    loc_ldh: "Doctors Hospital and Medical Center",
    loc_ldh_addr: "152-G, 1 Canal Rd, Block G1 Phase 1 Johar Town, Lahore, 54590",
    loc_ldh_hours: "Mon–Sat · 12:00 PM – 2:00 PM · Mon–Fri · 8:00 PM – 10:00 PM",
    loc_fh: "Farooq Hospital DHA",
    loc_fh_addr: "Avenue Mall, Main Ghazi Rd, DHA, Lahore, 54000",
    loc_fh_hours: "Mon–Sat · 5:00 PM – 7:00 PM",
    loc_directions: "Get directions",
    loc_call_reception: "Call",

    test_eyebrow: "Patient stories",
    test_title: "What patients say",
    test_1: "Dr. Ahmad explained my mother's dialysis options without rushing. We came in scared and left with a plan we understood.",
    test_1_name: "Ayesha K.",
    test_1_meta: "Daughter of patient",
    test_2: "Six years post-transplant and still thriving thanks to his follow-up. He never misses a detail.",
    test_2_name: "Tariq M.",
    test_2_meta: "Transplant recipient",
    test_3: "Finally got my blood pressure under control after years of trying. Calm, methodical, kind.",
    test_3_name: "Saima R.",
    test_3_meta: "Hypertension patient",

    faq_eyebrow: "Common questions",
    faq_title: "When should you see a nephrologist?",
    faq_1_q: "What does a nephrologist treat?",
    faq_1_a: "Nephrologists specialise in kidney health — including chronic kidney disease, kidney stones, dialysis, transplants, and the management of high blood pressure when it relates to kidney function.",
    faq_2_q: "When should I book a consultation?",
    faq_2_a: "If you have diabetes, persistent high blood pressure, swelling in the legs, foamy urine, family history of kidney disease, or have been told your creatinine is high — these are good reasons to come in.",
    faq_3_q: "Do I need a referral?",
    faq_3_a: "No referral is required. You can book directly. Bring any recent lab reports, imaging, and a list of medications.",
    faq_4_q: "What happens at the first visit?",
    faq_4_a: "A 30–45 minute consultation: review of history and reports, examination, and a discussion of next steps. Tests may be ordered if needed.",
    faq_5_q: "Is online consultation available?",
    faq_5_a: "Follow-up patients can request a phone consultation. First-time patients are seen in person to allow for proper examination.",

    book_step_hospital: "Hospital",
    book_step_time: "Date & time",
    book_step_details: "Your details",
    book_step_confirm: "Confirm",
    book_title: "Book an appointment",
    book_subtitle: "Most patients are seen within 3 working days.",
    book_choose_hospital: "Where would you like to be seen?",
    book_first_visit: "Is this a first visit or follow-up?",
    book_first: "First visit",
    book_followup: "Follow-up",
    book_choose_date: "Choose a date",
    book_choose_time: "Available time slots",
    book_morning: "Morning",
    book_afternoon: "Afternoon",
    book_evening: "Evening",
    book_no_slots: "No slots available",
    book_full_name: "Full name",
    book_phone: "Mobile number",
    book_cnic: "CNIC (optional)",
    book_age: "Age",
    book_gender: "Gender",
    book_male: "Male",
    book_female: "Female",
    book_other: "Other",
    book_reason: "Reason for visit",
    book_reason_ph: "Briefly describe your symptoms or concern…",
    book_continue: "Continue",
    book_back: "Back",
    book_confirm_btn: "Confirm appointment",
    book_summary: "Appointment summary",
    book_confirmed: "Appointment confirmed",
    book_confirmed_sub: "We will contact you to confirm your slot. Please arrive 15 minutes early with your previous reports and a list of current medications.",
    book_booking_id: "Booking ID",
    book_add_calendar: "Add to calendar",
    book_done: "Done",

    foot_tag: "Care, continuity, kidney health.",
    foot_links: "Links",
    foot_contact: "Contact",
    foot_hours: "Clinic hours",
    foot_emergency: "For emergencies, please go to the nearest hospital A&E.",
    foot_copy: "© 2026 Dr. Irfan Ahmad. All rights reserved.",
  },
  ur: {
    nav_about: "تعارف",
    nav_services: "خدمات",
    nav_locations: "مقامات",
    nav_faq: "سوالات",
    nav_book: "اپائنٹمنٹ",

    hero_eyebrow: "ماہر امراضِ گردہ · لاہور",
    hero_name: "ڈاکٹر عرفان احمد",
    hero_creds: "M.B.B.S · MRCPI · FRCPI · نیفرولوجی میں ہائر اسپیشلسٹ ٹریننگ · ڈپلومہ ان ذیابیطس UK",
    hero_role: "کنسلٹنٹ فزیشن، نیفرولوجسٹ اور ٹرانسپلانٹ اسپیشلسٹ",
    hero_subtitle: "ذیابیطس، بلڈ پریشر، گردوں کے امراض اور ٹرانسپلانٹ کے ماہر۔ آسٹریلیا اور برونائی میں نیفرولوجسٹ کے طور پر کام کر چکے ہیں۔ ڈاکٹرز ہسپتال اینڈ میڈیکل سینٹر لاہور اور فاروق ہسپتال ڈی ایچ اے لاہور میں خدمات۔",
    hero_cta_book: "اپائنٹمنٹ بک کریں",
    hero_cta_call: "کلینک کال کریں",
    hero_credential_title: "بین الاقوامی تربیت یافتہ",
    hero_credential_sub: "UK · آسٹریلیا · برونائی",

    stat_years: "سالہ تجربہ",
    stat_patients: "مریضوں کا علاج",
    stat_transplants: "ٹرانسپلانٹس",
    stat_rating: "مریضوں کی رائے",

    about_eyebrow: "تعارف",
    about_title: "ایک دہائی سے زائد عرصے سے گردوں اور ذیابیطس کے مریضوں کی دیکھ بھال۔",
    about_body_1: "ڈاکٹر عرفان احمد اختر سعید میڈیکل اینڈ ڈینٹل کالج لاہور میں نیفرولوجی کے ایسوسی ایٹ پروفیسر ہیں۔ وہ ڈاکٹرز ہسپتال اینڈ میڈیکل سینٹر لاہور اور فاروق ہسپتال ڈی ایچ اے لاہور میں کنسلٹنٹ فزیشن اور نیفرولوجسٹ کے طور پر خدمات انجام دیتے ہیں۔ ان کا کام جدید گردہ کی دیکھ بھال پر مرکوز ہے — دائمی گردہ کی بیماری، ڈائلیسس، اور گردہ ٹرانسپلانٹ — اس کے ساتھ ذیابیطس اور بلڈ پریشر کا طویل مدتی علاج۔",
    about_body_2: "انہوں نے رائل کالج آف فزیشنز آف آئرلینڈ سے MRCPI اور FRCPI مکمل کی، یونیورسٹی آف لیورپول سے آرگن ٹرانسپلانٹیشن میں سرٹیفکیٹ حاصل کیا، اور یوکے سے ذیابیطس میں ڈپلومہ بھی رکھتے ہیں۔",

    spec_eyebrow: "خصوصی شعبے",
    spec_title: "مہارت کے شعبے",
    spec_kidney: "گردوں کے امراض",
    spec_kidney_desc: "دائمی اور شدید گردہ کی بیماری، گلومیرولر امراض، ہیموڈائلیسس، پیریٹونیل ڈائلیسس اور گردے کی پتھری۔",
    spec_transplant: "ٹرانسپلانٹ",
    spec_transplant_desc: "گردہ ٹرانسپلانٹ کے لیے مریض کی تیاری، پوسٹ ٹرانسپلانٹ دیکھ بھال، امیونوسپریشن اور طویل مدتی فالو اپ۔",
    spec_diabetes: "ذیابیطس",
    spec_diabetes_desc: "ذیابیطس کا جامع علاج، گردوں کی حفاظت پر توجہ۔",
    spec_hyper: "بلڈ پریشر",
    spec_hyper_desc: "ضروری، ثانوی اور مزاحم بلڈ پریشر کا علاج، بشمول رینوواسکولر اسباب۔",
    spec_intervention: "مداخلتی طریقہ کار",
    spec_intervention_desc: "عارضی اور مستقل ڈائلیسس کیتھیٹر لگانا اور گردہ بائیوپسی۔",

    qual_eyebrow: "تربیت و اسناد",
    qual_title: "اسناد",
    qual_mbbs: "M.B.B.S",
    qual_mbbs_inst: "حمدرد یونیورسٹی، کراچی",
    qual_mrcp: "MRCPI — رکن، رائل کالج آف فزیشنز آف آئرلینڈ",
    qual_mrcp_inst: "رائل کالج آف فزیشنز آف آئرلینڈ",
    qual_frcp: "FRCPI — فیلو، رائل کالج آف فزیشنز آف آئرلینڈ",
    qual_frcp_inst: "رائل کالج آف فزیشنز آف آئرلینڈ",
    qual_hst: "نیفرولوجی میں ہائر اسپیشلسٹ ٹریننگ",
    qual_hst_inst: "بین الاقوامی اسپیشلسٹ ٹریننگ",
    qual_diab: "ڈپلومہ ان ذیابیطس",
    qual_diab_inst: "برطانیہ",
    qual_tx: "آرگن ٹرانسپلانٹیشن سرٹیفکیٹ",
    qual_tx_inst: "یونیورسٹی آف لیورپول",
    qual_assoc: "ایسوسی ایٹ پروفیسر، نیفرولوجی",
    qual_assoc_inst: "اختر سعید میڈیکل اینڈ ڈینٹل کالج",

    loc_eyebrow: "ہم کہاں ملتے ہیں",
    loc_title: "ہسپتال کے مقامات",
    loc_ldh: "ڈاکٹرز ہسپتال اینڈ میڈیکل سینٹر",
    loc_ldh_addr: "152-G، 1 کینال روڈ، بلاک G1 فیز 1 جوہر ٹاؤن، لاہور",
    loc_ldh_hours: "پیر تا ہفتہ · دوپہر 12 تا 2 · پیر تا جمعہ · رات 8 تا 10",
    loc_fh: "فاروق ہسپتال ڈی ایچ اے",
    loc_fh_addr: "ایونیو مال، مین غازی روڈ، ڈی ایچ اے، لاہور",
    loc_fh_hours: "پیر تا ہفتہ · شام 5 تا 7",
    loc_directions: "راستہ دیکھیں",
    loc_call_reception: "کال کریں",

    test_eyebrow: "مریضوں کی آراء",
    test_title: "مریض کیا کہتے ہیں",
    test_1: "ڈاکٹر صاحب نے میری والدہ کے ڈائلیسس کے سب آپشن تفصیل سے سمجھائے۔ ہم پریشان آئے، اطمینان سے گئے۔",
    test_1_name: "عائشہ ک.",
    test_1_meta: "مریضہ کی بیٹی",
    test_2: "ٹرانسپلانٹ کے چھ سال بعد بھی ٹھیک ہوں، ان کی فالو اپ کی بدولت۔",
    test_2_name: "طارق م.",
    test_2_meta: "ٹرانسپلانٹ ریسپینٹ",
    test_3: "آخرکار میرا بلڈ پریشر کنٹرول میں آیا۔ مہربان، تجربہ کار اور پرسکون۔",
    test_3_name: "صائمہ ر.",
    test_3_meta: "ہائپرٹینشن مریضہ",

    faq_eyebrow: "اکثر پوچھے گئے سوالات",
    faq_title: "نیفرولوجسٹ سے کب رجوع کریں؟",
    faq_1_q: "نیفرولوجسٹ کن امراض کا علاج کرتے ہیں؟",
    faq_1_a: "نیفرولوجسٹ گردوں کی صحت، ڈائلیسس، ٹرانسپلانٹ اور بلڈ پریشر کے ماہر ہوتے ہیں۔",
    faq_2_q: "کب اپائنٹمنٹ لینی چاہیے؟",
    faq_2_a: "ذیابیطس، بلڈ پریشر، ٹانگوں میں سوجن، یا کریٹینین زیادہ ہونے کی صورت میں رجوع کریں۔",
    faq_3_q: "کیا ریفرل ضروری ہے؟",
    faq_3_a: "نہیں، براہ راست بک کر سکتے ہیں۔ پرانی رپورٹیں اور دواؤں کی فہرست ساتھ لائیں۔",
    faq_4_q: "پہلی ملاقات میں کیا ہوگا؟",
    faq_4_a: "30–45 منٹ کی ملاقات: تاریخ، رپورٹس کا جائزہ، معائنہ اور آئندہ کے اقدامات۔",
    faq_5_q: "کیا آن لائن مشاورت دستیاب ہے؟",
    faq_5_a: "فالو اپ مریض فون پر مشاورت لے سکتے ہیں۔ پہلی ملاقات بالمشافہ ہوتی ہے۔",

    book_step_hospital: "ہسپتال",
    book_step_time: "تاریخ و وقت",
    book_step_details: "تفصیلات",
    book_step_confirm: "تصدیق",
    book_title: "اپائنٹمنٹ بک کریں",
    book_subtitle: "زیادہ تر مریضوں کو 3 دن میں دیکھا جاتا ہے۔",
    book_choose_hospital: "کہاں ملاقات کرنا چاہیں گے؟",
    book_first_visit: "پہلی ملاقات یا فالو اپ؟",
    book_first: "پہلی ملاقات",
    book_followup: "فالو اپ",
    book_choose_date: "تاریخ منتخب کریں",
    book_choose_time: "دستیاب اوقات",
    book_morning: "صبح",
    book_afternoon: "دوپہر",
    book_evening: "شام",
    book_no_slots: "کوئی وقت دستیاب نہیں",
    book_full_name: "پورا نام",
    book_phone: "موبائل نمبر",
    book_cnic: "شناختی کارڈ (اختیاری)",
    book_age: "عمر",
    book_gender: "جنس",
    book_male: "مرد",
    book_female: "خاتون",
    book_other: "دیگر",
    book_reason: "ملاقات کی وجہ",
    book_reason_ph: "علامات یا تشویش مختصراً لکھیں…",
    book_continue: "آگے",
    book_back: "واپس",
    book_confirm_btn: "اپائنٹمنٹ کنفرم کریں",
    book_summary: "اپائنٹمنٹ کا خلاصہ",
    book_confirmed: "اپائنٹمنٹ تصدیق شدہ",
    book_confirmed_sub: "ہم آپ کی سلاٹ کی تصدیق کے لیے رابطہ کریں گے۔ مہربانی فرما کر 15 منٹ پہلے پہنچیں۔",
    book_booking_id: "بکنگ آئی ڈی",
    book_add_calendar: "کیلنڈر میں شامل کریں",
    book_done: "ختم",

    foot_tag: "گردوں کی صحت — خیال، تسلسل، اعتبار۔",
    foot_links: "روابط",
    foot_contact: "رابطہ",
    foot_hours: "اوقاتِ کلینک",
    foot_emergency: "ایمرجنسی کی صورت میں قریبی ہسپتال کے ایمرجنسی ڈیپارٹمنٹ سے رجوع کریں۔",
    foot_copy: "© 2026 ڈاکٹر عرفان احمد۔ جملہ حقوق محفوظ ہیں۔",
  },
} as const;

export type StringKey = keyof typeof STRINGS.en;

export function useT(lang: Lang) {
  return (key: StringKey): string =>
    (STRINGS[lang] as Record<string, string>)[key] ?? STRINGS.en[key] ?? key;
}

export function formatDate(d: Date, lang: Lang): string {
  const months =
    lang === "ur"
      ? ["جنوری","فروری","مارچ","اپریل","مئی","جون","جولائی","اگست","ستمبر","اکتوبر","نومبر","دسمبر"]
      : ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return `${d.getDate()} ${months[d.getMonth()]} ${d.getFullYear()}`;
}
